# Generated by Django 2.2.6 on 2020-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'saturday'), ('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=12)),
                ('solt', models.TimeField()),
                ('courseTitle', models.CharField(max_length=20)),
                ('teacherIni', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=10)),
            ],
        ),
    ]
