# Generated by Django 2.2.6 on 2020-05-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='courseTitle',
            field=models.CharField(max_length=50),
        ),
    ]
