# Generated by Django 2.2.6 on 2020-04-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=8)),
                ('courseTitle', models.CharField(max_length=20)),
                ('topic', models.TextField()),
                ('data', models.DateField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
