# Generated by Django 2.2.6 on 2020-04-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20200417_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='data',
            new_name='date',
        ),
    ]
