# Generated by Django 2.2.6 on 2020-04-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=8)),
                ('courseTitle', models.CharField(max_length=20)),
                ('last', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
