# Generated by Django 2.2.6 on 2020-04-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_assigment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assigment',
            new_name='assignment',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='last',
            new_name='lastDate',
        ),
    ]
