# Generated by Django 2.2.6 on 2020-05-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='courseTitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='courseTitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='courseTitle',
            field=models.CharField(max_length=50),
        ),
    ]
